"""
Global constants for the Sentinel synthetic merchant data generator.

Every numeric assumption in this module is a synthetic modeling choice made
for benchmark construction. None of it is derived from real Razorpay,
merchant, or industry data. See docs/data_generation.md for the full
list of assumptions.
"""

from __future__ import annotations

from datetime import date

# ---------------------------------------------------------------------------
# Benchmark sizing
# ---------------------------------------------------------------------------

# Initial prototype benchmark (per PROJECT_CONTEXT.md).
DEFAULT_N_MERCHANTS = 50
DEFAULT_N_DAYS = 180
DEFAULT_SEED = 42

# Fixed synthetic anchor date. Arbitrary and stable across regenerations —
# NOT tied to any real calendar event. Day-of-week / day-of-year seasonality
# is computed relative to this anchor.
DEFAULT_START_DATE = date(2024, 1, 1)

# Final scale target the generator must support without redesign
# (per PROJECT_CONTEXT.md "Final target"). Not generated by default.
SCALE_TARGET_N_MERCHANTS = 500
SCALE_TARGET_N_DAYS = 365

# ---------------------------------------------------------------------------
# Merchant archetypes (exact set required by PROJECT_CONTEXT.md)
# ---------------------------------------------------------------------------

ARCHETYPES = [
    "D2C Fashion",
    "Electronics",
    "SaaS",
    "Travel",
    "Marketplace",
    "Education",
    "Quick Commerce",
    "Digital Goods",
]

BUSINESS_TIERS = ["small", "mid", "large"]
BUSINESS_TIER_WEIGHTS = [0.50, 0.35, 0.15]

PAYMENT_METHODS = ["card", "upi", "netbanking", "wallet", "bnpl"]

# ---------------------------------------------------------------------------
# Event / scenario taxonomy
# ---------------------------------------------------------------------------

EVENT_CATEGORY_RISK = "risk"
EVENT_CATEGORY_BENIGN_GROWTH = "benign_growth"

# event_type -> category. Every event generated by the simulator must use
# one of these types; this is the single source of truth for the taxonomy.
EVENT_TYPES = {
    "chargeback_deterioration": EVENT_CATEGORY_RISK,
    "refund_shock": EVENT_CATEGORY_RISK,
    "fulfillment_degradation": EVENT_CATEGORY_RISK,
    "customer_mix_shift": EVENT_CATEGORY_RISK,
    "compound_risk": EVENT_CATEGORY_RISK,
    "festival_growth": EVENT_CATEGORY_BENIGN_GROWTH,
    "viral_campaign": EVENT_CATEGORY_BENIGN_GROWTH,
    "product_launch": EVENT_CATEGORY_BENIGN_GROWTH,
    "payment_method_shift": EVENT_CATEGORY_BENIGN_GROWTH,
}

RISK_EVENT_TYPES = [t for t, c in EVENT_TYPES.items() if c == EVENT_CATEGORY_RISK]
BENIGN_GROWTH_EVENT_TYPES = [
    t for t, c in EVENT_TYPES.items() if c == EVENT_CATEGORY_BENIGN_GROWTH
]

# Relative sampling weights across event types (must cover all EVENT_TYPES).
# Kept close to balanced between risk and benign-growth so the benchmark does
# not implicitly teach "risk is rare" or "growth is rare".
EVENT_TYPE_WEIGHTS = {
    "chargeback_deterioration": 0.14,
    "refund_shock": 0.12,
    "fulfillment_degradation": 0.12,
    "customer_mix_shift": 0.10,
    "compound_risk": 0.07,
    "festival_growth": 0.16,
    "viral_campaign": 0.11,
    "product_launch": 0.09,
    "payment_method_shift": 0.09,
}

# Probability that a given instance of an event type uses a "gradual" ramp
# (smooth multi-day onset) rather than a "sudden" one (near-immediate onset).
# Deliberately not 1.0/0.0 everywhere: real deterioration is *usually*
# gradual but not exclusively, and real growth spikes sometimes ARE sudden
# (viral_campaign) — the benchmark must not let the model shortcut on
# "sudden shape == risk".
EVENT_GRADUAL_PROBABILITY = {
    "chargeback_deterioration": 0.90,
    "refund_shock": 0.50,
    "fulfillment_degradation": 0.85,
    "customer_mix_shift": 0.80,
    "compound_risk": 0.85,
    "festival_growth": 0.60,
    "viral_campaign": 0.10,
    "product_launch": 0.70,
    "payment_method_shift": 0.95,
}

# Mean gap (days) between sampled event start candidates, per merchant.
# Larger mean -> sparser events. Tuned only for plausible density at the
# 180-365 day scale, not to hit any target model metric.
EVENT_MEAN_GAP_DAYS = 35.0

# Fixed, n_days-independent stopping bound for event-candidate scheduling.
# Keeping this constant (rather than deriving it from n_days) is what makes
# the schedule invariant to the requested window length — see
# events.schedule_candidate_events() and tests/test_data_generation.py
# (leakage / truncation-invariance tests).
EVENT_SCHEDULE_HORIZON_DAYS = 3650

# ---------------------------------------------------------------------------
# RNG stream purpose codes.
#
# Each independently-seeded RNG stream is derived from
# (seed, purpose_code, *ids) via numpy.random.SeedSequence. Keeping streams
# separated by purpose (and never sharing one stream across a quantity whose
# call-count depends on n_days) is what guarantees:
#   1. full reproducibility for a fixed seed, and
#   2. truncation invariance (generating fewer days never changes earlier
#      days' values) which is the direct test for absence of look-ahead.
# ---------------------------------------------------------------------------

RNG_PURPOSE_MERCHANT_STATIC = 1
RNG_PURPOSE_EVENT_SCHEDULE = 2
RNG_PURPOSE_DAILY = 3

# ---------------------------------------------------------------------------
# Label construction
# ---------------------------------------------------------------------------

LABEL_HORIZONS_DAYS = [7, 14, 30]

# Trailing window (days, ending at and including t) used to compute a
# merchant's own historical baseline for label thresholding. This uses only
# information available at/before t.
LABEL_TRAILING_WINDOW_DAYS = 28

# A future window is classified "materially elevated" if the realized
# chargeback amount exceeds this multiple of the trailing-baseline-implied
# expectation for that window.
LABEL_ELEVATION_RATIO_THRESHOLD = 1.75

# Absolute floor (synthetic currency units) below which a future chargeback
# amount is never labeled "elevated", regardless of ratio — avoids labeling
# noise on merchants with near-zero baseline chargebacks.
LABEL_MIN_ABSOLUTE_FLOOR = 50.0

# Materiality floor expressed as a fraction of trailing daily GMV * horizon.
LABEL_MIN_GMV_FRACTION_FLOOR = 0.0005
